package dev.lifesteal;

import org.bukkit.Bukkit;
import org.bukkit.GameMode;
import org.bukkit.World;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.potion.PotionEffect;
import org.bukkit.NamespacedKey;
import org.bukkit.configuration.file.YamlConfiguration;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.Base64;

public final class DataStore {
    private final LifeStealPlugin plugin; private final File outsideDir; private File groupFile; private YamlConfiguration groups;
    public DataStore(LifeStealPlugin plugin){this.plugin=plugin;outsideDir=new File(plugin.getDataFolder(),"outside-state");if(!outsideDir.exists())outsideDir.mkdirs();}
    private void ensureGroups(World world){File dir=new File(world.getWorldFolder(),"lifesteal-data");if(!dir.exists())dir.mkdirs();groupFile=new File(dir,"groups.yml");groups=YamlConfiguration.loadConfiguration(groupFile);}
    private File lifeFile(World world,UUID id){File d=new File(world.getWorldFolder(),"lifesteal-data");if(!d.exists())d.mkdirs();return new File(d,id+".yml");}
    private void saveGroups(){try{groups.save(groupFile);}catch(IOException e){plugin.getLogger().warning("Could not save groups.yml: "+e.getMessage());}}
    public PlayerData loadLifeStealData(Player p){return loadLifeStealData(p.getUniqueId(),p.getWorld());}
    public PlayerData loadLifeStealData(UUID id,World world){ensureGroups(world);YamlConfiguration c=YamlConfiguration.loadConfiguration(lifeFile(world,id));PlayerData d=new PlayerData(c.getInt("hearts",plugin.startingHearts()));d.eliminated=c.getBoolean("eliminated",false);d.kills=c.getInt("kills",0);return d;}
    public void saveLifeStealData(Player p,PlayerData d){saveLifeStealData(p.getUniqueId(),p.getName(),p.getWorld(),d);}
    public void saveLifeStealData(UUID id,String name,World world,PlayerData d){ensureGroups(world);YamlConfiguration c=new YamlConfiguration();c.set("uuid",id.toString());c.set("name",name);c.set("hearts",d.hearts);c.set("eliminated",d.eliminated);c.set("kills",d.kills);try{c.save(lifeFile(world,id));}catch(IOException e){plugin.getLogger().warning("Could not save LifeSteal data: "+e.getMessage());}}
    public void saveLifeStealState(Player p){ensureGroups(p.getWorld());saveState(lifeFile(p.getWorld(),p.getUniqueId()),p);groups.set(p.getUniqueId().toString(),"lifesteal");saveGroups();}
    public void saveOutsideState(Player p){saveState(new File(outsideDir,p.getUniqueId()+".yml"),p);if(plugin.mainWorld()!=null)ensureGroups(plugin.mainWorld());else ensureGroups(p.getWorld());groups.set(p.getUniqueId().toString(),"outside");saveGroups();}
    public StateData loadLifeStealState(Player p){return loadState(lifeFile(p.getWorld(),p.getUniqueId()));}
    public StateData loadOutsideState(Player p){return loadState(new File(outsideDir,p.getUniqueId()+".yml"));}
    public String getMarker(World world,UUID id){ensureGroups(world);return groups.getString(id.toString());}
    public void setMarker(World world,UUID id,String side){ensureGroups(world);groups.set(id.toString(),side);saveGroups();}
    public List<UUID> eliminatedPlayers(World world){ensureGroups(world);File[] fs=groupFile.getParentFile().listFiles((d,n)->n.endsWith(".yml")&&!n.equals("groups.yml"));List<UUID> out=new ArrayList<>();if(fs==null)return out;for(File f:fs){YamlConfiguration c=YamlConfiguration.loadConfiguration(f);if(c.getBoolean("eliminated",false))try{out.add(UUID.fromString(f.getName().substring(0,f.getName().length()-4)));}catch(Exception ignored){}}return out;}
    public String playerName(World world,UUID id){ensureGroups(world);return YamlConfiguration.loadConfiguration(lifeFile(world,id)).getString("name",id.toString());}
    private void saveState(File f,Player p){YamlConfiguration c=new YamlConfiguration();c.set("location.world",p.getWorld().getName());c.set("location.x",p.getLocation().getX());c.set("location.y",p.getLocation().getY());c.set("location.z",p.getLocation().getZ());c.set("location.yaw",p.getLocation().getYaw());c.set("location.pitch",p.getLocation().getPitch());c.set("inventory",encode(p.getInventory().getContents()));c.set("armor",encode(p.getInventory().getArmorContents()));c.set("offhand",encode(new ItemStack[]{p.getInventory().getItemInOffHand()}));c.set("ender",encode(enderContents(p)));c.set("xp.level",p.getLevel());c.set("xp.progress",p.getExp());c.set("xp.total",p.getTotalExperience());c.set("health",p.getHealth());c.set("max-health",Objects.requireNonNull(p.getAttribute(org.bukkit.attribute.Attribute.MAX_HEALTH)).getBaseValue());c.set("food",p.getFoodLevel());c.set("saturation",p.getSaturation());c.set("exhaustion",p.getExhaustion());c.set("fire-ticks",p.getFireTicks());c.set("air",p.getRemainingAir());c.set("gamemode",p.getGameMode().name());List<Map<String,Object>> effects=new ArrayList<>();for(PotionEffect e:p.getActivePotionEffects()){Map<String,Object> m=new HashMap<>();m.put("type",e.getType().getKey().toString());m.put("duration",e.getDuration());m.put("amplifier",e.getAmplifier());m.put("ambient",e.isAmbient());m.put("particles",e.hasParticles());m.put("icon",e.hasIcon());effects.add(m);}c.set("effects",effects);try{f.getParentFile().mkdirs();c.save(f);}catch(IOException e){plugin.getLogger().warning("Could not save player state: "+e.getMessage());}}
    private StateData loadState(File f){if(!f.exists())return null;YamlConfiguration c=YamlConfiguration.loadConfiguration(f);StateData s=new StateData();s.contents=decode(c.getString("inventory"));s.armor=decode(c.getString("armor"));ItemStack[] off=decode(c.getString("offhand"));s.offhand=off.length==0?null:off[0];s.enderChest=decode(c.getString("ender"));s.level=c.getInt("xp.level");s.exp=(float)c.getDouble("xp.progress");s.totalExperience=c.getInt("xp.total");s.health=c.getDouble("health",20);s.maxHealth=c.getDouble("max-health",20);s.food=c.getInt("food",20);s.saturation=(float)c.getDouble("saturation",5);s.exhaustion=(float)c.getDouble("exhaustion",0);s.fireTicks=c.getInt("fire-ticks",0);s.air=c.getInt("air",400);try{s.gameMode=GameMode.valueOf(c.getString("gamemode","SURVIVAL"));}catch(Exception e){s.gameMode=GameMode.SURVIVAL;}List<?> list=c.getList("effects",List.of());s.effects=new ArrayList<>();for(Object o:list)if(o instanceof Map<?,?> m)try{String key=String.valueOf(m.get("type"));var type=org.bukkit.Registry.POTION_EFFECT_TYPE.get(NamespacedKey.fromString(key));if(type!=null)s.effects.add(new PotionEffect(type,Integer.parseInt(String.valueOf(m.get("duration"))),Integer.parseInt(String.valueOf(m.get("amplifier"))),Boolean.parseBoolean(String.valueOf(m.get("ambient"))),Boolean.parseBoolean(String.valueOf(m.get("particles"))),Boolean.parseBoolean(String.valueOf(m.get("icon")))));}catch(Exception ignored){}World w=Bukkit.getWorld(c.getString("location.world"));if(w!=null)s.location=new org.bukkit.Location(w,c.getDouble("location.x"),c.getDouble("location.y"),c.getDouble("location.z"),(float)c.getDouble("location.yaw"),(float)c.getDouble("location.pitch"));return s;}
    private ItemStack[] enderContents(Player p){ItemStack[] a=new ItemStack[p.getEnderChest().getSize()];for(int i=0;i<a.length;i++)a[i]=p.getEnderChest().getItem(i);return a;}
    private String encode(ItemStack[] items){try{return Base64.getEncoder().encodeToString(ItemStack.serializeItemsAsBytes(items));}catch(Exception e){return "";}}
    private ItemStack[] decode(String s){if(s==null||s.isBlank())return new ItemStack[0];try{return ItemStack.deserializeItemsFromBytes(Base64.getDecoder().decode(s));}catch(Exception e){return new ItemStack[0];}}
    public void applyState(Player p,StateData s,boolean clean){p.getInventory().clear();p.getEnderChest().clear();p.setFireTicks(0);p.setRemainingAir(p.getMaximumAir());p.setFoodLevel(20);p.setSaturation(5);p.setExhaustion(0);p.setLevel(0);p.setExp(0);p.setTotalExperience(0);for(PotionEffect e:p.getActivePotionEffects())p.removePotionEffect(e.getType());if(s==null||clean){Objects.requireNonNull(p.getAttribute(org.bukkit.attribute.Attribute.MAX_HEALTH)).setBaseValue(20);p.setHealth(20);p.setGameMode(GameMode.SURVIVAL);return;}p.getInventory().setContents(s.contents==null?new ItemStack[p.getInventory().getSize()]:s.contents);p.getInventory().setArmorContents(s.armor==null?new ItemStack[4]:s.armor);p.getInventory().setItemInOffHand(s.offhand);for(int i=0;i<p.getEnderChest().getSize()&&i<(s.enderChest==null?0:s.enderChest.length);i++)p.getEnderChest().setItem(i,s.enderChest[i]);p.setLevel(s.level);p.setExp(Math.max(0,Math.min(1,s.exp)));p.setTotalExperience(s.totalExperience);Objects.requireNonNull(p.getAttribute(org.bukkit.attribute.Attribute.MAX_HEALTH)).setBaseValue(Math.max(1,s.maxHealth));p.setHealth(Math.max(0.1,Math.min(s.health,s.maxHealth)));p.setFoodLevel(Math.max(0,Math.min(20,s.food)));p.setSaturation(s.saturation);p.setExhaustion(s.exhaustion);p.setFireTicks(s.fireTicks);p.setRemainingAir(Math.max(0,Math.min(p.getMaximumAir(),s.air)));for(PotionEffect e:s.effects)p.addPotionEffect(e);p.setGameMode(s.gameMode);}
}